# Generated by Django 4.0.3 on 2022-04-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
